In [ ]:
import numpy as np


In [ ]:
list1=[10,20,30,40]
arr1=np.array(list1)
print(arr1)
print(arr1.dtype)

[10 20 30 40]
int64


In [ ]:
arr2=np.zeros(5)
print(arr2)
print(arr2.dtype)
print(len(arr2))
print(arr2.size)

[0. 0. 0. 0. 0.]
float64
5
5


In [ ]:
arr3= np.zeros(shape=(2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr3= np.zeros(shape=(2,3),dtype="int")
print(arr3)
print(len(arr3))
print(arr3.size)

[[0 0 0]
 [0 0 0]]
2
6


In [ ]:
list1=[
    [10,20,30],
    [30,40,50]
]
arr2=np.array(list1)
print(arr2)

[[10 20 30]
 [30 40 50]]


In [ ]:
arrr=np.array([
    [10,20,30],
    [30,40,50]
])

print(arrr)

[[10 20 30]
 [30 40 50]]


In [ ]:
arrr1=np.array([
    [10,20,30],
    [30,40,50]
])
arrr2=np.array([
    [10,20,30],
    [30,40,50]
])

print(arrr1+arrr2)
print(arrr1-arrr2)


[[ 20  40  60]
 [ 60  80 100]]
[[0 0 0]
 [0 0 0]]


In [ ]:
arrr1=np.array([
    [10,20,30],
    [30,40,50]
])
arrr2=np.array([
    [10,20,30],
    [30,42,51]
])
arrr3=arrr1.T
print(arrr3)

[[10 30]
 [20 40]
 [30 50]]


In [ ]:
arr1=np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [ ]:
arr1=10*np.ones(5)
print(arr1)

[10. 10. 10. 10. 10.]


In [ ]:
#range(start,stop(exclusive),step)
arr1=np.arange(10, 20, 2)
print(arr1)

[10 12 14 16 18]


In [ ]:
arr1=np.arange(10, 20, 1)
print(arr1)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
range=(10,20,2.5)
print(range)

(10, 20, 2.5)


In [ ]:
arrr1=np.array([
    [10,20,30],
    [30,40,50]
])
print(arrr1.shape)
print(arrr1.shape[0])
print(arrr1.shape[1])

(2, 3)
2
3


In [ ]:
idn=np.eye(5)
print(idn)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
idn=np.identity(5)
print(idn)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
idn=100*np.eye(5)
print(idn)

[[100.   0.   0.   0.   0.]
 [  0. 100.   0.   0.   0.]
 [  0.   0. 100.   0.   0.]
 [  0.   0.   0. 100.   0.]
 [  0.   0.   0.   0. 100.]]


In [ ]:
arr1=np.array([
    [10,20,30],
    [30,40,50]
])
arr2=np.array([
    [10,20,30],
    [30,42,51]
])
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[[ 100  400  900]
 [ 900 1680 2550]]
[[1.         1.         1.        ]
 [1.         0.95238095 0.98039216]]
[[ 0  0  0]
 [ 0 40 50]]


In [ ]:
#actual matrix multiplication
arr1=np.array([
    [10,20,30],
    [30,40,50]
])
arr2=np.array([
    [10,20],
    [30,42],
    [51,60]
])
print(arr1 @ arr2)

[[2230 2840]
 [4050 5280]]


In [ ]:
#broadcasting
arr1=np.array([
    [10,20,30],
    [30,40,50],
    [30,42,51]
])
arr2=np.array([
    [10,20,30]
])
print(arr1*arr2)
print(arr1+5)

[[ 100  400  900]
 [ 300  800 1500]
 [ 300  840 1530]]
[[15 25 35]
 [35 45 55]
 [35 47 56]]


In [ ]:
arr1=np.array([
    [10,20,30],
    [30,40,50],
    [30,42,51]
])
arr3=arr1.flatten() # creates a new array
print(arr3)
arr4=arr1.ravel() # doesn't create a new array.

print(arr4)

[10 20 30 30 40 50 30 42 51]
[10 20 30 30 40 50 30 42 51]


In [ ]:
import pandas as pd

In [ ]:
#dataseries
list1=[10,20,30,40]
ser1=pd.Series(list1)
print(ser1)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
print(ser1.index)

RangeIndex(start=0, stop=4, step=1)


In [ ]:
print(ser1.values)

[10 20 30 40]


In [ ]:
idx=['a','b','c','d']
list1=[10,20,30,40]
ser2=pd.Series(list1,index=idx)
print(ser2)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
idx=['a','b','c','d']
list1=[10,20,30,40]
ser2=pd.Series(list1,idx)
print(ser2)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
#dataframe
loc= "/content/Iris.csv"
df=pd.read_csv(loc)
print(df)

FileNotFoundError: [Errno 2] No such file or directory: '/content/Iris.csv'

In [ ]:
df.head()

In [ ]:
df.head(10)

In [ ]:
df.tail()

In [ ]:
df.tail(10)

In [ ]:
print(df.shape)

In [ ]:
df.info()

In [ ]:
df.describe() # shows the statistical values of features

In [ ]:
# checking null values count
df.isnull().sum()

In [ ]:
df.value_counts("Species")

In [ ]:
list1=150*[100]
print(list1)
df["New"]=list1
print(df)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x=np.array([0,6])
y=np.array([10,40])
plt.plot(x,y)
plt.show()

In [ ]:
points=[3,8,5,6,20]
plt.plot(points, marker="o", linestyle="dotted", color="r")
plt.show()

In [ ]:
x=np.arange(-10, 11, 1)
print(x)
y=x**2
print(y)
plt.title("y=x*x")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid()# put it before the plot
plt.plot(x,y)
plt.show()

In [ ]:
x=np.arange(-10, 11, 1)
print(x)
y=x**2
print(y)
plt.title("y=x*x")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid()# put it before the plot
plt.scatter(x,y, color="orange",marker="_")
plt.show()

In [ ]:
x=df["SepalLengthCm"]
y=df["SepalWidthCm"]
plt.scatter(x,y)
plt.plot(x,y)
plt.show()

In [ ]:
x=np.arange(-10, 11,1)

y1=x**2
plt.subplot(3,2,1)
plt.plot(x,y1)

y2=x**3
plt.subplot(3,2,2)
plt.plot(x,y2)

y3=2*x
plt.subplot(3,2,3)
plt.plot(x,y3)

y4=np.sin(x)
plt.subplot(3,2,4)
plt.plot(x,y4)

y5=x-2
plt.subplot(3,2,5)
plt.plot(x,y5)

y6=3*x**2+5
plt.subplot(3,2,6)
plt.plot(x,y6)
plt.show()

In [ ]:
x=np.random.normal(150,20,200)
#print(x)
plt.hist(x)
#plt.show()